import {
    Box,
    Calendar,
    Folders,
    Navigation,
    Newspaper,
    FileText as PagesIcon,
    Settings,
    Target,
    Users,
    Users as UsersIcon,
    Activity,
    Link,
    Network,
    FolderTree,
    MessageSquare,
    Megaphone,
    BarChart3,
    BookA,
    HelpCircle,
    UserCheck,
    Heart,
    GitBranch,
    Lightbulb,
    Star,
    Search,
    Bell,
    FileCheck2,
    Globe,
    LayoutDashboard,
    Table,
    LayoutGrid,
    GraduationCap,
    Award,
    TrendingUp,
    ClipboardList,
    Upload,
} from "lucide-react";

// ============================================================================
// CATEGORY IDS
// ============================================================================

export const CATEGORY_IDS = {
    COMMUNICATION: 'communication',
    KNOWLEDGE: 'knowledge',
    HR_TALENT: 'hr-talent',
    BUSINESS: 'business',
    COLLABORATION: 'collaboration',
    SYSTEM: 'system',
    CUSTOM_DEVELOPMENT: 'custom-development',
} as const;

export type ModuleCategoryId = typeof CATEGORY_IDS[keyof typeof CATEGORY_IDS];

// ============================================================================
// MODULE IDS
// ============================================================================

export const MODULE_IDS = {
    DOCUMENT_LIBRARY: "DOCUMENT_LIBRARY",
    EVENT: "EVENT",
    INSTALLED_MODULE: "INSTALLED_MODULE",
    MISC: "MISC",
    NAVIGATION: "NAVIGATION",
    NEWS: "NEWS",
    PAGE: "PAGE",
    PEOPLE_DIRECTORY: "PEOPLE_DIRECTORY",
    POLYGON: "POLYGON",
    PUBLISH_ACTIVITY: "PUBLISH_ACTIVITY",
    SETTING: "SETTING",
    USEFUL_LINKS: "USEFUL_LINKS",
    CUSTOM_LIST: "CUSTOM_LIST",
    USERS_AND_GROUPS: "USERS_AND_GROUPS",
    UNIVERSAL_SEARCH: "UNIVERSAL_SEARCH",
    SMART_NOTIFICATIONS: "SMART_NOTIFICATIONS",
    SMART_FORMS: "SMART_FORMS",
    MULTI_SITE_HUB: "MULTI_SITE_HUB",
    DASHBOARD_BUILDER: "DASHBOARD_BUILDER",
    FORUM: "FORUM",
    ANNOUNCEMENTS: "ANNOUNCEMENTS",
    POLLS_SURVEYS: "POLLS_SURVEYS",
    GLOSSARY: "GLOSSARY",
    FAQ: "FAQ",
    ONBOARDING: "ONBOARDING",
    WELLBEING_HUB: "WELLBEING_HUB",
    WORKFLOW_AUTOMATION: "WORKFLOW_AUTOMATION",
    CLIENT_TESTIMONIALS: "CLIENT_TESTIMONIALS",
    LEARNING_ACADEMY: "LEARNING_ACADEMY",
    SKILLS_HUB: "SKILLS_HUB",
    CAREER_MOBILITY: "CAREER_MOBILITY",
    ASSESSMENTS: "ASSESSMENTS",
    SUGGESTION_BOX: "SUGGESTION_BOX",
    CUSTOM_BNPP_VJ2: "CUSTOM_BNPP_VJ2",
} as const;

export type TModuleId = typeof MODULE_IDS[keyof typeof MODULE_IDS];

// Extraction automatique des IDs de modules pour l'enum Zod
export const moduleIds = Object.values(MODULE_IDS) as [TModuleId, ...TModuleId[]];

// ============================================================================
// MODULE CATEGORIES
// ============================================================================

export const MODULE_CATEGORIES = {
    COMMUNICATION: {
        id: CATEGORY_IDS.COMMUNICATION,
        titleKey: 'moduleCategories.communication.title',
        descriptionKey: 'moduleCategories.communication.description',
    },
    KNOWLEDGE: {
        id: CATEGORY_IDS.KNOWLEDGE,
        titleKey: 'moduleCategories.knowledge.title',
        descriptionKey: 'moduleCategories.knowledge.description',
    },
    HR_TALENT: {
        id: CATEGORY_IDS.HR_TALENT,
        titleKey: 'moduleCategories.hrTalent.title',
        descriptionKey: 'moduleCategories.hrTalent.description',
    },
    BUSINESS: {
        id: CATEGORY_IDS.BUSINESS,
        titleKey: 'moduleCategories.business.title',
        descriptionKey: 'moduleCategories.business.description',
    },
    COLLABORATION: {
        id: CATEGORY_IDS.COLLABORATION,
        titleKey: 'moduleCategories.collaboration.title',
        descriptionKey: 'moduleCategories.collaboration.description',
    },
    SYSTEM: {
        id: CATEGORY_IDS.SYSTEM,
        titleKey: 'moduleCategories.system.title',
        descriptionKey: 'moduleCategories.system.description',
    },
    CUSTOM_DEVELOPMENT: {
        id: CATEGORY_IDS.CUSTOM_DEVELOPMENT,
        titleKey: 'moduleCategories.customDevelopment.title',
        descriptionKey: 'moduleCategories.customDevelopment.description',
    },
} as const;

// ============================================================================
// MODULES MAP
// ============================================================================

export const MODULES_MAP = {
    "./document-library/module.config": {
        id: MODULE_IDS.DOCUMENT_LIBRARY,
        titleKey: `modules.${MODULE_IDS.DOCUMENT_LIBRARY}.title`,
        descriptionKey: `modules.${MODULE_IDS.DOCUMENT_LIBRARY}.description`,
        category: CATEGORY_IDS.KNOWLEDGE,
        Icon: FolderTree,
        url: "./document-library/module.config",
        inDevelopment: false,
        fragments: {
            documentLibrary: {
                id: "DOCUMENT_LIBRARY",
                titleKey: `modules.${MODULE_IDS.DOCUMENT_LIBRARY}.fragments.documentLibrary.title`,
                descriptionKey: `modules.${MODULE_IDS.DOCUMENT_LIBRARY}.fragments.documentLibrary.description`,
                Icon: FolderTree,
            },
        },
    },
    "./event/module.config": {
        id: MODULE_IDS.EVENT,
        titleKey: `modules.${MODULE_IDS.EVENT}.title`,
        descriptionKey: `modules.${MODULE_IDS.EVENT}.description`,
        category: CATEGORY_IDS.COMMUNICATION,
        Icon: Calendar,
        url: "./event/module.config",
        inDevelopment: false,
        fragments: {
            eventItems: {
                id: "EVENT_ITEMS",
                titleKey: `modules.${MODULE_IDS.EVENT}.fragments.eventItems.title`,
                descriptionKey: 'modules.event.fragments.eventItems.description',
                Icon: Calendar,
            },
            eventCategories: {
                id: "EVENT_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.EVENT}.fragments.eventCategories.title`,
                descriptionKey: 'modules.event.fragments.eventCategories.description',
                Icon: Box,
            },
        },
    },
    "./installed-module/module.config": {
        id: MODULE_IDS.INSTALLED_MODULE,
        titleKey: `modules.${MODULE_IDS.INSTALLED_MODULE}.title`,
        descriptionKey: `modules.${MODULE_IDS.INSTALLED_MODULE}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: LayoutGrid,
        url: "./installed-module/module.config",
        inDevelopment: false,
        fragments: {
            installedModules: {
                id: "INSTALLED_MODULES",
                titleKey: `modules.${MODULE_IDS.INSTALLED_MODULE}.fragments.installedModules.title`,
                descriptionKey: `modules.${MODULE_IDS.INSTALLED_MODULE}.fragments.installedModules.description`,
                Icon: LayoutGrid,
            },
        },
    },
    "./misc/module.config": {
        id: MODULE_IDS.MISC,
        titleKey: `modules.${MODULE_IDS.MISC}.title`,
        descriptionKey: `modules.${MODULE_IDS.MISC}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: Box,
        url: "./misc/module.config",
        inDevelopment: false,
        fragments: {
            miscLibrary: {
                id: "MISC_LIBRARY",
                titleKey: `modules.${MODULE_IDS.MISC}.fragments.miscLibrary.title`,
                descriptionKey: 'modules.misc.fragments.miscLibrary.description',
                Icon: Folders,
            },
        },
    },
    "./navigation/module.config": {
        id: MODULE_IDS.NAVIGATION,
        titleKey: `modules.${MODULE_IDS.NAVIGATION}.title`,
        descriptionKey: `modules.${MODULE_IDS.NAVIGATION}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: Navigation,
        url: "./navigation/module.config",
        inDevelopment: false,
        fragments: {
            headerNavigationItems: {
                id: "HEADER_NAVIGATION_ITEMS",
                titleKey: `modules.${MODULE_IDS.NAVIGATION}.fragments.headerNavigationItems.title`,
                descriptionKey: `modules.${MODULE_IDS.NAVIGATION}.fragments.headerNavigationItems.description`,
                Icon: Navigation,
            },
            footerNavigationItems: {
                id: "FOOTER_NAVIGATION_ITEMS",
                titleKey: `modules.${MODULE_IDS.NAVIGATION}.fragments.footerNavigationItems.title`,
                descriptionKey: `modules.${MODULE_IDS.NAVIGATION}.fragments.footerNavigationItems.description`,
                Icon: Navigation,
            },
        },
    },
    "./news/module.config": {
        id: MODULE_IDS.NEWS,
        titleKey: `modules.${MODULE_IDS.NEWS}.title`,
        descriptionKey: `modules.${MODULE_IDS.NEWS}.description`,
        category: CATEGORY_IDS.COMMUNICATION,
        Icon: Newspaper,
        url: "./news/module.config",
        inDevelopment: false,
        fragments: {
            newsItems: {
                id: "NEWS_ITEMS",
                titleKey: `modules.${MODULE_IDS.NEWS}.fragments.newsItems.title`,
                descriptionKey: `modules.${MODULE_IDS.NEWS}.fragments.newsItems.description`,
                Icon: Newspaper,
            },
            newsCategories: {
                id: "NEWS_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.NEWS}.fragments.newsCategories.title`,
                descriptionKey: `modules.${MODULE_IDS.NEWS}.fragments.newsCategories.description`,
                Icon: Box,
            },
        },
    },
    "./page/module.config": {
        id: MODULE_IDS.PAGE,
        titleKey: `modules.${MODULE_IDS.PAGE}.title`,
        descriptionKey: `modules.${MODULE_IDS.PAGE}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: PagesIcon,
        url: "./page/module.config",
        inDevelopment: false,
        fragments: {
            pages: {
                id: "PAGE",
                titleKey: `modules.${MODULE_IDS.PAGE}.fragments.pages.title`,
                descriptionKey: 'modules.page.fragments.pages.description',
                Icon: PagesIcon,
            },
        },
    },
    "./people-directory/module.config": {
        id: MODULE_IDS.PEOPLE_DIRECTORY,
        titleKey: `modules.${MODULE_IDS.PEOPLE_DIRECTORY}.title`,
        descriptionKey: `modules.${MODULE_IDS.PEOPLE_DIRECTORY}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: UsersIcon,
        url: "./people-directory/module.config",
        inDevelopment: false,
        fragments: {
            peopleDirectoryItems: {
                id: "PEOPLE_DIRECTORY_ITEMS",
                titleKey: `modules.${MODULE_IDS.PEOPLE_DIRECTORY}.fragments.peopleDirectoryItems.title`,
                descriptionKey: 'modules.peopleDirectory.fragments.peopleDirectoryItems.description',
                Icon: Users,
            },
            peopleDirectoryCategories: {
                id: "PEOPLE_DIRECTORY_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.PEOPLE_DIRECTORY}.fragments.peopleDirectoryCategories.title`,
                descriptionKey: 'modules.peopleDirectory.fragments.peopleDirectoryCategories.description',
                Icon: Network,
            },
        },
    },
    "./polygon/module.config": {
        id: MODULE_IDS.POLYGON,
        titleKey: `modules.${MODULE_IDS.POLYGON}.title`,
        descriptionKey: `modules.${MODULE_IDS.POLYGON}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: Target,
        url: "./polygon/module.config",
        inDevelopment: false,
        fragments: {},
    },
    "./publish-activity/module.config": {
        id: MODULE_IDS.PUBLISH_ACTIVITY,
        titleKey: `modules.${MODULE_IDS.PUBLISH_ACTIVITY}.title`,
        descriptionKey: `modules.${MODULE_IDS.PUBLISH_ACTIVITY}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: Activity,
        url: "./publish-activity/module.config",
        inDevelopment: false,
        fragments: {
            publishActivityItems: {
                id: "PUBLISH_ACTIVITY_ITEMS",
                titleKey: `modules.${MODULE_IDS.PUBLISH_ACTIVITY}.fragments.publishActivityItems.title`,
                descriptionKey: 'modules.publishActivity.fragments.publishActivityItems.description',
                Icon: Activity,
            },
        },
    },
    "./setting/module.config": {
        id: MODULE_IDS.SETTING,
        titleKey: `modules.${MODULE_IDS.SETTING}.title`,
        descriptionKey: `modules.${MODULE_IDS.SETTING}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: Settings,
        url: "./setting/module.config",
        inDevelopment: false,
        fragments: {
            settings: {
                id: "SETTINGS",
                titleKey: `modules.${MODULE_IDS.SETTING}.fragments.settings.title`,
                descriptionKey: `modules.${MODULE_IDS.SETTING}.fragments.settings.description`,
                Icon: Settings,
            },
        },
    },
    "./useful-links/module.config": {
        id: MODULE_IDS.USEFUL_LINKS,
        titleKey: `modules.${MODULE_IDS.USEFUL_LINKS}.title`,
        descriptionKey: `modules.${MODULE_IDS.USEFUL_LINKS}.description`,
        category: CATEGORY_IDS.KNOWLEDGE,
        Icon: Link,
        url: "./useful-links/module.config",
        inDevelopment: false,
        fragments: {
            usefulLinkItems: {
                id: "USEFUL_LINK_ITEMS",
                titleKey: `modules.${MODULE_IDS.USEFUL_LINKS}.fragments.usefulLinkItems.title`,
                descriptionKey: 'modules.usefulLinks.fragments.usefulLinkItems.description',
                Icon: Link,
            },
            usefulLinkCategories: {
                id: "USEFUL_LINK_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.USEFUL_LINKS}.fragments.usefulLinkCategories.title`,
                descriptionKey: 'modules.usefulLinks.fragments.usefulLinkCategories.description',
                Icon: Box,
            },
        },
    },
    "./custom-list/module.config": {
        id: MODULE_IDS.CUSTOM_LIST,
        titleKey: `modules.${MODULE_IDS.CUSTOM_LIST}.title`,
        descriptionKey: `modules.${MODULE_IDS.CUSTOM_LIST}.description`,
        category: CATEGORY_IDS.COLLABORATION,
        Icon: Table,
        url: "./custom-list/module.config",
        inDevelopment: true,
        fragments: {
            customLists: {
                id: "CUSTOM_LISTS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_LIST}.fragments.customLists.title`,
                descriptionKey: 'modules.customList.fragments.customLists.description',
                Icon: Table,
            },
            customListTemplates: {
                id: "CUSTOM_LIST_TEMPLATES",
                titleKey: `modules.${MODULE_IDS.CUSTOM_LIST}.fragments.customListTemplates.title`,
                descriptionKey: 'modules.customList.fragments.customListTemplates.description',
                Icon: Folders,
            },
        },
    },
    "./users-and-groups/module.config": {
        id: MODULE_IDS.USERS_AND_GROUPS,
        titleKey: `modules.${MODULE_IDS.USERS_AND_GROUPS}.title`,
        descriptionKey: `modules.${MODULE_IDS.USERS_AND_GROUPS}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: Users,
        url: "./users-and-groups/module.config",
        inDevelopment: false,
        fragments: {
            groups: {
                id: "GROUPS",
                titleKey: `modules.${MODULE_IDS.USERS_AND_GROUPS}.fragments.groups.title`,
                descriptionKey: 'modules.usersAndGroups.fragments.groups.description',
                Icon: Users,
            },
            users: {
                id: "USERS",
                titleKey: `modules.${MODULE_IDS.USERS_AND_GROUPS}.fragments.users.title`,
                descriptionKey: 'modules.usersAndGroups.fragments.users.description',
                Icon: Users,
            },
        },
    },
    "./universal-search/module.config": {
        id: MODULE_IDS.UNIVERSAL_SEARCH,
        titleKey: `modules.${MODULE_IDS.UNIVERSAL_SEARCH}.title`,
        descriptionKey: `modules.${MODULE_IDS.UNIVERSAL_SEARCH}.description`,
        category: CATEGORY_IDS.COLLABORATION,
        Icon: Search,
        url: "./universal-search/module.config",
        inDevelopment: true,
        fragments: {
            searchIndex: {
                id: "SEARCH_INDEX",
                titleKey: `modules.${MODULE_IDS.UNIVERSAL_SEARCH}.fragments.searchIndex.title`,
                descriptionKey: 'modules.universalSearch.fragments.searchIndex.description',
                Icon: Search,
            },
        },
    },
    "./smart-notifications/module.config": {
        id: MODULE_IDS.SMART_NOTIFICATIONS,
        titleKey: `modules.${MODULE_IDS.SMART_NOTIFICATIONS}.title`,
        descriptionKey: `modules.${MODULE_IDS.SMART_NOTIFICATIONS}.description`,
        category: CATEGORY_IDS.COLLABORATION,
        Icon: Bell,
        url: "./smart-notifications/module.config",
        inDevelopment: true,
        fragments: {
            notificationRules: {
                id: "NOTIFICATION_RULES",
                titleKey: `modules.${MODULE_IDS.SMART_NOTIFICATIONS}.fragments.notificationRules.title`,
                descriptionKey: 'modules.smartNotifications.fragments.notificationRules.description',
                Icon: Bell,
            },
            notificationHistory: {
                id: "NOTIFICATION_HISTORY",
                titleKey: `modules.${MODULE_IDS.SMART_NOTIFICATIONS}.fragments.notificationHistory.title`,
                descriptionKey: 'modules.smartNotifications.fragments.notificationHistory.description',
                Icon: Activity,
            },
        },
    },
    "./smart-forms/module.config": {
        id: MODULE_IDS.SMART_FORMS,
        titleKey: `modules.${MODULE_IDS.SMART_FORMS}.title`,
        descriptionKey: `modules.${MODULE_IDS.SMART_FORMS}.description`,
        category: CATEGORY_IDS.COLLABORATION,
        Icon: FileCheck2,
        url: "./smart-forms/module.config",
        inDevelopment: true,
        fragments: {
            formTemplates: {
                id: "FORM_TEMPLATES",
                titleKey: `modules.${MODULE_IDS.SMART_FORMS}.fragments.formTemplates.title`,
                descriptionKey: 'modules.smartForms.fragments.formTemplates.description',
                Icon: FileCheck2,
            },
            formSubmissions: {
                id: "FORM_SUBMISSIONS",
                titleKey: `modules.${MODULE_IDS.SMART_FORMS}.fragments.formSubmissions.title`,
                descriptionKey: 'modules.smartForms.fragments.formSubmissions.description',
                Icon: Activity,
            },
        },
    },
    "./multi-site-hub/module.config": {
        id: MODULE_IDS.MULTI_SITE_HUB,
        titleKey: `modules.${MODULE_IDS.MULTI_SITE_HUB}.title`,
        descriptionKey: `modules.${MODULE_IDS.MULTI_SITE_HUB}.description`,
        category: CATEGORY_IDS.COLLABORATION,
        Icon: Globe,
        url: "./multi-site-hub/module.config",
        inDevelopment: true,
        fragments: {
            connectedSites: {
                id: "CONNECTED_SITES",
                titleKey: `modules.${MODULE_IDS.MULTI_SITE_HUB}.fragments.connectedSites.title`,
                descriptionKey: 'modules.multiSiteHub.fragments.connectedSites.description',
                Icon: Globe,
            },
            aggregatedContent: {
                id: "AGGREGATED_CONTENT",
                titleKey: `modules.${MODULE_IDS.MULTI_SITE_HUB}.fragments.aggregatedContent.title`,
                descriptionKey: 'modules.multiSiteHub.fragments.aggregatedContent.description',
                Icon: Network,
            },
        },
    },
    "./dashboard-builder/module.config": {
        id: MODULE_IDS.DASHBOARD_BUILDER,
        titleKey: `modules.${MODULE_IDS.DASHBOARD_BUILDER}.title`,
        descriptionKey: `modules.${MODULE_IDS.DASHBOARD_BUILDER}.description`,
        category: CATEGORY_IDS.BUSINESS,
        Icon: LayoutDashboard,
        url: "./dashboard-builder/module.config",
        inDevelopment: true,
        fragments: {
            dashboards: {
                id: "DASHBOARDS",
                titleKey: `modules.${MODULE_IDS.DASHBOARD_BUILDER}.fragments.dashboards.title`,
                descriptionKey: 'modules.dashboardBuilder.fragments.dashboards.description',
                Icon: LayoutDashboard,
            },
            widgets: {
                id: "WIDGETS",
                titleKey: `modules.${MODULE_IDS.DASHBOARD_BUILDER}.fragments.widgets.title`,
                descriptionKey: 'modules.dashboardBuilder.fragments.widgets.description',
                Icon: Box,
            },
        },
    },
    "./forum/module.config": {
        id: MODULE_IDS.FORUM,
        titleKey: `modules.${MODULE_IDS.FORUM}.title`,
        descriptionKey: `modules.${MODULE_IDS.FORUM}.description`,
        category: CATEGORY_IDS.COMMUNICATION,
        Icon: MessageSquare,
        url: "./forum/module.config",
        inDevelopment: true,
        fragments: {
            forumTopics: {
                id: "FORUM_TOPICS",
                titleKey: `modules.${MODULE_IDS.FORUM}.fragments.forumTopics.title`,
                descriptionKey: 'modules.forum.fragments.forumTopics.description',
                Icon: MessageSquare,
            },
            forumCategories: {
                id: "FORUM_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.FORUM}.fragments.forumCategories.title`,
                descriptionKey: 'modules.forum.fragments.forumCategories.description',
                Icon: Box,
            },
        },
    },
    "./announcements/module.config": {
        id: MODULE_IDS.ANNOUNCEMENTS,
        titleKey: `modules.${MODULE_IDS.ANNOUNCEMENTS}.title`,
        descriptionKey: `modules.${MODULE_IDS.ANNOUNCEMENTS}.description`,
        category: CATEGORY_IDS.COMMUNICATION,
        Icon: Megaphone,
        url: "./announcements/module.config",
        inDevelopment: true,
        fragments: {
            announcementItems: {
                id: "ANNOUNCEMENT_ITEMS",
                titleKey: `modules.${MODULE_IDS.ANNOUNCEMENTS}.fragments.announcementItems.title`,
                descriptionKey: 'modules.announcements.fragments.announcementItems.description',
                Icon: Megaphone,
            },
        },
    },
    "./polls-surveys/module.config": {
        id: MODULE_IDS.POLLS_SURVEYS,
        titleKey: `modules.${MODULE_IDS.POLLS_SURVEYS}.title`,
        descriptionKey: `modules.${MODULE_IDS.POLLS_SURVEYS}.description`,
        category: CATEGORY_IDS.COMMUNICATION,
        Icon: BarChart3,
        url: "./polls-surveys/module.config",
        inDevelopment: true,
        fragments: {
            pollItems: {
                id: "POLL_ITEMS",
                titleKey: `modules.${MODULE_IDS.POLLS_SURVEYS}.fragments.pollItems.title`,
                descriptionKey: 'modules.pollsSurveys.fragments.pollItems.description',
                Icon: BarChart3,
            },
        },
    },
    "./glossary/module.config": {
        id: MODULE_IDS.GLOSSARY,
        titleKey: `modules.${MODULE_IDS.GLOSSARY}.title`,
        descriptionKey: `modules.${MODULE_IDS.GLOSSARY}.description`,
        category: CATEGORY_IDS.KNOWLEDGE,
        Icon: BookA,
        url: "./glossary/module.config",
        inDevelopment: true,
        fragments: {
            glossaryTerms: {
                id: "GLOSSARY_TERMS",
                titleKey: `modules.${MODULE_IDS.GLOSSARY}.fragments.glossaryTerms.title`,
                descriptionKey: 'modules.glossary.fragments.glossaryTerms.description',
                Icon: BookA,
            },
        },
    },
    "./faq/module.config": {
        id: MODULE_IDS.FAQ,
        titleKey: `modules.${MODULE_IDS.FAQ}.title`,
        descriptionKey: `modules.${MODULE_IDS.FAQ}.description`,
        category: CATEGORY_IDS.KNOWLEDGE,
        Icon: HelpCircle,
        url: "./faq/module.config",
        inDevelopment: false,
        fragments: {
            faqItems: {
                id: "FAQ_ITEMS",
                titleKey: `modules.${MODULE_IDS.FAQ}.fragments.faqItems.title`,
                descriptionKey: 'modules.faq.fragments.faqItems.description',
                Icon: HelpCircle,
            },
            faqCategories: {
                id: "FAQ_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.FAQ}.fragments.faqCategories.title`,
                descriptionKey: 'modules.faq.fragments.faqCategories.description',
                Icon: Box,
            },
        },
    },
    "./onboarding/module.config": {
        id: MODULE_IDS.ONBOARDING,
        titleKey: `modules.${MODULE_IDS.ONBOARDING}.title`,
        descriptionKey: `modules.${MODULE_IDS.ONBOARDING}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: UserCheck,
        url: "./onboarding/module.config",
        inDevelopment: true,
        fragments: {
            onboardingTasks: {
                id: "ONBOARDING_TASKS",
                titleKey: `modules.${MODULE_IDS.ONBOARDING}.fragments.onboardingTasks.title`,
                descriptionKey: 'modules.onboarding.fragments.onboardingTasks.description',
                Icon: UserCheck,
            },
            onboardingResources: {
                id: "ONBOARDING_RESOURCES",
                titleKey: `modules.${MODULE_IDS.ONBOARDING}.fragments.onboardingResources.title`,
                descriptionKey: 'modules.onboarding.fragments.onboardingResources.description',
                Icon: Folders,
            },
        },
    },
    "./wellbeing-hub/module.config": {
        id: MODULE_IDS.WELLBEING_HUB,
        titleKey: `modules.${MODULE_IDS.WELLBEING_HUB}.title`,
        descriptionKey: `modules.${MODULE_IDS.WELLBEING_HUB}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: Heart,
        url: "./wellbeing-hub/module.config",
        inDevelopment: true,
        fragments: {
            wellnessPrograms: {
                id: "WELLNESS_PROGRAMS",
                titleKey: `modules.${MODULE_IDS.WELLBEING_HUB}.fragments.wellnessPrograms.title`,
                descriptionKey: 'modules.wellbeingHub.fragments.wellnessPrograms.description',
                Icon: Heart,
            },
            wellnessResources: {
                id: "WELLNESS_RESOURCES",
                titleKey: `modules.${MODULE_IDS.WELLBEING_HUB}.fragments.wellnessResources.title`,
                descriptionKey: 'modules.wellbeingHub.fragments.wellnessResources.description',
                Icon: Folders,
            },
        },
    },
    "./workflow-automation/module.config": {
        id: MODULE_IDS.WORKFLOW_AUTOMATION,
        titleKey: `modules.${MODULE_IDS.WORKFLOW_AUTOMATION}.title`,
        descriptionKey: `modules.${MODULE_IDS.WORKFLOW_AUTOMATION}.description`,
        category: CATEGORY_IDS.SYSTEM,
        Icon: GitBranch,
        url: "./workflow-automation/module.config",
        inDevelopment: false,
        fragments: {
            workflowItems: {
                id: "WORKFLOW_ITEMS",
                titleKey: `modules.${MODULE_IDS.WORKFLOW_AUTOMATION}.fragments.workflowItems.title`,
                descriptionKey: `modules.${MODULE_IDS.WORKFLOW_AUTOMATION}.fragments.workflowItems.description`,
                Icon: GitBranch,
            },
        },
    },
    "./client-testimonials/module.config": {
        id: MODULE_IDS.CLIENT_TESTIMONIALS,
        titleKey: `modules.${MODULE_IDS.CLIENT_TESTIMONIALS}.title`,
        descriptionKey: `modules.${MODULE_IDS.CLIENT_TESTIMONIALS}.description`,
        category: CATEGORY_IDS.BUSINESS,
        Icon: Star,
        url: "./client-testimonials/module.config",
        inDevelopment: true,
        fragments: {
            testimonials: {
                id: "TESTIMONIALS",
                titleKey: `modules.${MODULE_IDS.CLIENT_TESTIMONIALS}.fragments.testimonials.title`,
                descriptionKey: 'modules.clientTestimonials.fragments.testimonials.description',
                Icon: Star,
            },
        },
    },
    "./learning-academy/module.config": {
        id: MODULE_IDS.LEARNING_ACADEMY,
        titleKey: `modules.${MODULE_IDS.LEARNING_ACADEMY}.title`,
        descriptionKey: `modules.${MODULE_IDS.LEARNING_ACADEMY}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: GraduationCap,
        url: "./learning-academy/module.config",
        inDevelopment: true,
        fragments: {
            trainingCourses: {
                id: "TRAINING_COURSES",
                titleKey: `modules.${MODULE_IDS.LEARNING_ACADEMY}.fragments.trainingCourses.title`,
                descriptionKey: 'modules.learningAcademy.fragments.trainingCourses.description',
                Icon: GraduationCap,
            },
            learningPaths: {
                id: "LEARNING_PATHS",
                titleKey: `modules.${MODULE_IDS.LEARNING_ACADEMY}.fragments.learningPaths.title`,
                descriptionKey: 'modules.learningAcademy.fragments.learningPaths.description',
                Icon: TrendingUp,
            },
            certifications: {
                id: "CERTIFICATIONS",
                titleKey: `modules.${MODULE_IDS.LEARNING_ACADEMY}.fragments.certifications.title`,
                descriptionKey: 'modules.learningAcademy.fragments.certifications.description',
                Icon: Award,
            },
            trainingCategories: {
                id: "TRAINING_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.LEARNING_ACADEMY}.fragments.trainingCategories.title`,
                descriptionKey: 'modules.learningAcademy.fragments.trainingCategories.description',
                Icon: Box,
            },
        },
    },
    "./skills-hub/module.config": {
        id: MODULE_IDS.SKILLS_HUB,
        titleKey: `modules.${MODULE_IDS.SKILLS_HUB}.title`,
        descriptionKey: `modules.${MODULE_IDS.SKILLS_HUB}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: Award,
        url: "./skills-hub/module.config",
        inDevelopment: true,
        fragments: {
            skills: {
                id: "SKILLS",
                titleKey: `modules.${MODULE_IDS.SKILLS_HUB}.fragments.skills.title`,
                descriptionKey: 'modules.skillsHub.fragments.skills.description',
                Icon: Award,
            },
            skillTypes: {
                id: "SKILL_TYPES",
                titleKey: `modules.${MODULE_IDS.SKILLS_HUB}.fragments.skillTypes.title`,
                descriptionKey: 'modules.skillsHub.fragments.skillTypes.description',
                Icon: Box,
            },
            skillLevels: {
                id: "SKILL_LEVELS",
                titleKey: `modules.${MODULE_IDS.SKILLS_HUB}.fragments.skillLevels.title`,
                descriptionKey: 'modules.skillsHub.fragments.skillLevels.description',
                Icon: BarChart3,
            },
            employeeSkills: {
                id: "EMPLOYEE_SKILLS",
                titleKey: `modules.${MODULE_IDS.SKILLS_HUB}.fragments.employeeSkills.title`,
                descriptionKey: 'modules.skillsHub.fragments.employeeSkills.description',
                Icon: Users,
            },
        },
    },
    "./career-mobility/module.config": {
        id: MODULE_IDS.CAREER_MOBILITY,
        titleKey: `modules.${MODULE_IDS.CAREER_MOBILITY}.title`,
        descriptionKey: `modules.${MODULE_IDS.CAREER_MOBILITY}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: TrendingUp,
        url: "./career-mobility/module.config",
        inDevelopment: true,
        fragments: {
            opportunities: {
                id: "OPPORTUNITIES",
                titleKey: `modules.${MODULE_IDS.CAREER_MOBILITY}.fragments.opportunities.title`,
                descriptionKey: 'modules.careerMobility.fragments.opportunities.description',
                Icon: TrendingUp,
            },
            mobilityActors: {
                id: "MOBILITY_ACTORS",
                titleKey: `modules.${MODULE_IDS.CAREER_MOBILITY}.fragments.mobilityActors.title`,
                descriptionKey: 'modules.careerMobility.fragments.mobilityActors.description',
                Icon: UserCheck,
            },
            careerPaths: {
                id: "CAREER_PATHS",
                titleKey: `modules.${MODULE_IDS.CAREER_MOBILITY}.fragments.careerPaths.title`,
                descriptionKey: 'modules.careerMobility.fragments.careerPaths.description',
                Icon: Network,
            },
            mobilityMetrics: {
                id: "MOBILITY_METRICS",
                titleKey: `modules.${MODULE_IDS.CAREER_MOBILITY}.fragments.mobilityMetrics.title`,
                descriptionKey: 'modules.careerMobility.fragments.mobilityMetrics.description',
                Icon: BarChart3,
            },
        },
    },
    "./assessments/module.config": {
        id: MODULE_IDS.ASSESSMENTS,
        titleKey: `modules.${MODULE_IDS.ASSESSMENTS}.title`,
        descriptionKey: `modules.${MODULE_IDS.ASSESSMENTS}.description`,
        category: CATEGORY_IDS.HR_TALENT,
        Icon: ClipboardList,
        url: "./assessments/module.config",
        inDevelopment: true,
        fragments: {
            questionnaires: {
                id: "QUESTIONNAIRES",
                titleKey: `modules.${MODULE_IDS.ASSESSMENTS}.fragments.questionnaires.title`,
                descriptionKey: 'modules.assessments.fragments.questionnaires.description',
                Icon: ClipboardList,
            },
            questions: {
                id: "QUESTIONS",
                titleKey: `modules.${MODULE_IDS.ASSESSMENTS}.fragments.questions.title`,
                descriptionKey: 'modules.assessments.fragments.questions.description',
                Icon: HelpCircle,
            },
            questionCategories: {
                id: "QUESTION_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.ASSESSMENTS}.fragments.questionCategories.title`,
                descriptionKey: 'modules.assessments.fragments.questionCategories.description',
                Icon: Box,
            },
            assessmentResults: {
                id: "ASSESSMENT_RESULTS",
                titleKey: `modules.${MODULE_IDS.ASSESSMENTS}.fragments.assessmentResults.title`,
                descriptionKey: 'modules.assessments.fragments.assessmentResults.description',
                Icon: BarChart3,
            },
        },
    },
    "./suggestion-box/module.config": {
        id: MODULE_IDS.SUGGESTION_BOX,
        titleKey: `modules.${MODULE_IDS.SUGGESTION_BOX}.title`,
        descriptionKey: `modules.${MODULE_IDS.SUGGESTION_BOX}.description`,
        category: CATEGORY_IDS.COLLABORATION,
        Icon: Lightbulb,
        url: "./suggestion-box/module.config",
        inDevelopment: false,
        fragments: {
            ideaItems: {
                id: "IDEA_ITEMS",
                titleKey: `modules.${MODULE_IDS.SUGGESTION_BOX}.fragments.ideaItems.title`,
                descriptionKey: 'modules.suggestionBox.fragments.ideaItems.description',
                Icon: Lightbulb,
            },
            ideaCategories: {
                id: "IDEA_CATEGORIES",
                titleKey: `modules.${MODULE_IDS.SUGGESTION_BOX}.fragments.ideaCategories.title`,
                descriptionKey: 'modules.suggestionBox.fragments.ideaCategories.description',
                Icon: Box,
            },
        },
    },
    "./custom-bnpp-vj2/module.config": {
        id: MODULE_IDS.CUSTOM_BNPP_VJ2,
        titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.title`,
        descriptionKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.description`,
        catalogLogos: {
            light: "https://webexprdev.sharepoint.com/sites/Polygon/Custom%20Modules%20%20Logos/BNP%20Paribas/logo-light.svg",
            dark: "https://webexprdev.sharepoint.com/sites/Polygon/Custom%20Modules%20%20Logos/BNP%20Paribas/logo-dark.svg",
        },
        category: CATEGORY_IDS.CUSTOM_DEVELOPMENT,
        Icon: GraduationCap,
        url: "./custom-bnpp-vj2/module.config",
        inDevelopment: false,
        fragments: {
            contracts: {
                id: "CONTRACTS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.contracts.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.contracts.description',
                Icon: ClipboardList,
            },
            entity1: {
                id: "ENTITY_1",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.entity1.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.entity1.description',
                Icon: Network,
            },
            entity2: {
                id: "ENTITY_2",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.entity2.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.entity2.description',
                Icon: Network,
            },
            schools: {
                id: "SCHOOLS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.schools.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.schools.description',
                Icon: GraduationCap,
            },
            programs: {
                id: "PROGRAMS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.programs.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.programs.description',
                Icon: BookA,
            },
            skillItems: {
                id: "SKILL_ITEMS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.skillItems.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.skillItems.description',
                Icon: Star,
            },
            workFamilies: {
                id: "WORK_FAMILIES",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.workFamilies.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.workFamilies.description',
                Icon: Folders,
            },
            actionTypeHRBP: {
                id: "ACTION_TYPE_HRBP",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.actionTypeHRBP.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.actionTypeHRBP.description',
                Icon: ClipboardList,
            },
            actionTypeSBP: {
                id: "ACTION_TYPE_SBP",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.actionTypeSBP.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.actionTypeSBP.description',
                Icon: ClipboardList,
            },
            actionHRBP: {
                id: "ACTION_HRBP",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.actionHRBP.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.actionHRBP.description',
                Icon: ClipboardList,
            },
            actionSBP: {
                id: "ACTION_SBP",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.actionSBP.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.actionSBP.description',
                Icon: ClipboardList,
            },
            importLog: {
                id: "IMPORT_LOG",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.importLog.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.importLog.description',
                Icon: Upload,
            },
            studentAnswers: {
                id: "STUDENT_ANSWERS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.studentAnswers.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.studentAnswers.description',
                Icon: ClipboardList,
            },
            managerAnswers: {
                id: "MANAGER_ANSWERS",
                titleKey: `modules.${MODULE_IDS.CUSTOM_BNPP_VJ2}.fragments.managerAnswers.title`,
                descriptionKey: 'modules.CUSTOM_BNPP_VJ2.fragments.managerAnswers.description',
                Icon: ClipboardList,
            },
        },
    },
} as const;

// ============================================================================
// TYPES
// ============================================================================

export type TModule = typeof MODULES_MAP[keyof typeof MODULES_MAP];
export type TModuleCategory = typeof MODULE_CATEGORIES[keyof typeof MODULE_CATEGORIES];
